### ISSUE TITLE
add an example with subfolder

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/npm-install-action-example#1]
For https://github.com/bahmutov/npm-install/issues/51

```yml
jobs:
  npm:
    name: Install/Cache Node Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend-server
```
